spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ecommerce-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/ecommerce}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000
momo:
  partner-code: ${MOMO_PARTNER_CODE}
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_SECRET_KEY}
  api-url: https://test-payment.momo.vn/v2/gateway/api/create
  redirect-url: ${MOMO_REDIRECT_URL}
  ipn-url: ${MOMO_IPN_URL}
