spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ecommerce-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce
    username: postgres
    password: ${DB_PASSWORD:hthien23}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000
