spring:
  application:
    name: ecommerce-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: "hthien23"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true