
    create table cart_items (
        quantity integer not null check (quantity>=1),
        cart_id bigint not null,
        id bigint generated by default as identity,
        product_variant_id bigint not null,
        primary key (id),
        unique (cart_id, product_variant_id)
    );

    create table carts (
        id bigint generated by default as identity,
        user_id bigint not null unique,
        primary key (id)
    );

    create table categories (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table idempotency_keys (
        created_at timestamp(6),
        id varchar(255) not null,
        primary key (id)
    );

    create table order_items (
        price numeric(38,2) not null,
        quantity integer not null check (quantity>=1),
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint not null,
        size varchar(255),
        primary key (id)
    );

    create table orders (
        shipping_fee numeric(38,2),
        total_price numeric(38,2) not null,
        create_at timestamp(6),
        id bigint generated by default as identity,
        user_id bigint not null,
        version bigint,
        customer_name varchar(255),
        customer_phone varchar(255),
        payment_method varchar(255) check (payment_method in ('COD','MOMO')),
        shipping_address varchar(255),
        shipping_city varchar(255),
        shipping_method varchar(255),
        shipping_ward varchar(255),
        status varchar(255) not null check (status in ('AWAITING_PAYMENT','PENDING','CONFIRMED','SHIPPING','DONE','CANCELLED')),
        primary key (id)
    );

    create table payments (
        amount numeric(38,2),
        created_at timestamp(6),
        id bigint generated by default as identity,
        order_id bigint unique,
        updated_at timestamp(6),
        version bigint,
        momo_order_id varchar(255),
        momo_request_id varchar(255),
        payment_method varchar(255) check (payment_method in ('COD','MOMO')),
        payment_status varchar(255) check (payment_status in ('PENDING','PAID','FAILED','REFUNDED','REFUNDING')),
        transaction_id varchar(255),
        primary key (id)
    );

    create table product_variants (
        stock integer not null check (stock>=0),
        id bigint generated by default as identity,
        product_id bigint not null,
        version bigint,
        size_value varchar(255) not null,
        primary key (id),
        unique (product_id, size_value)
    );

    create table products (
        price numeric(38,2) not null check (price>=0),
        category_id bigint,
        id bigint generated by default as identity,
        version bigint,
        description TEXT,
        image_url varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table refresh_tokens (
        revoked boolean not null,
        expiry_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        user_id bigint not null,
        token_hash varchar(512) unique,
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        password varchar(255) not null,
        role varchar(255) check (role in ('ADMIN','USER')),
        primary key (id)
    );

    alter table if exists cart_items 
       add constraint FKpcttvuq4mxppo8sxggjtn5i2c 
       foreign key (cart_id) 
       references carts;

    alter table if exists cart_items 
       add constraint FKn1s4l7h0vm4o259wpu7ft0y2y 
       foreign key (product_variant_id) 
       references product_variants;

    alter table if exists carts 
       add constraint FKb5o626f86h46m4s7ms6ginnop 
       foreign key (user_id) 
       references users;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists payments 
       add constraint FK81gagumt0r8y3rmudcgpbk42l 
       foreign key (order_id) 
       references orders;

    alter table if exists product_variants 
       add constraint FKosqitn4s405cynmhb87lkvuau 
       foreign key (product_id) 
       references products;

    alter table if exists products 
       add constraint FKog2rp4qthbtt2lfyhfo32lsw9 
       foreign key (category_id) 
       references categories;

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;
